workflows:
ios-workflow:
name: iOS Unsigned Build

```
environment:
  xcode: latest

scripts:
  - name: Install CocoaPods
    script: |
      cd src
      pod install

  - name: Build iOS (no signing)
    script: |
      cd src
      xcodebuild \
      -workspace imsakiye.xcworkspace \
      -scheme imsakiye \
      -configuration Release \
      -sdk iphoneos \
      -destination 'generic/platform=iOS' \
      CODE_SIGNING_ALLOWED=NO \
      CODE_SIGNING_REQUIRED=NO \
      CODE_SIGN_IDENTITY="" \
      build

  - name: Create IPA
    script: |
      cd src
      mkdir -p Payload
      cp -R build/Release-iphoneos/imsakiye.app Payload
      zip -r imsakiye.ipa Payload

artifacts:
  - src/*.ipa
```
