workflows:
  ios-workflow:
    name: iOS Workflow

    environment:
      xcode: latest

    scripts:
      - name: Install CocoaPods
        script: |
          cd src
          pod install

      - name: Build iOS archive
        script: |
          cd src
          xcodebuild -workspace imsakiye.xcworkspace \
          -scheme imsakiye \
          -configuration Release \
          -sdk iphoneos \
          -destination 'generic/platform=iOS' \
          -archivePath build/imsakiye.xcarchive \
          archive

      - name: Export IPA
        script: |
          cd src
          mkdir -p build
          xcodebuild -exportArchive \
          -archivePath build/imsakiye.xcarchive \
          -exportOptionsPlist ExportOptions.plist \
          -exportPath build

    artifacts:
      - src/build/**/*.ipa
